// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZA7JNBd84t5dr0SR8PrELNYLii7jqAaw',
    appId: '1:152166275320:android:5c5ba45042bd1af89ac30d',
    messagingSenderId: '152166275320',
    projectId: 'tithe-box',
    storageBucket: 'tithe-box.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4nDHo8MY6MWp5QZrSHJrla_vBHFOIPuo',
    appId: '1:152166275320:ios:0e4f2ff26bc9147e9ac30d',
    messagingSenderId: '152166275320',
    projectId: 'tithe-box',
    storageBucket: 'tithe-box.appspot.com',
    androidClientId: '152166275320-52atoltn6hln1mos8clu4obd9p0tos6r.apps.googleusercontent.com',
    iosClientId: '152166275320-c4kalgagblabcti678itdmicm5ocidth.apps.googleusercontent.com',
    iosBundleId: 'com.morpheus.titheBox',
  );
}
